version: 2
jobs:
  build_android_m75_16:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          command: apt-get update && apt-get install -y make lsb-release net-tools git curl python openjdk-8-jdk-headless
      - run:
          command: update-java-alternatives -s java-1.8.0-openjdk-amd64
      - run:
          command: make android-m75.16
          no_output_timeout: 2h
  build_ios_m75_16:
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run:
          command: make ios-m75.16
          no_output_timeout: 2h


workflows:
  version: 2
  weekly_build_workflow:
    triggers:
      - schedule:
          # 週 1 、日曜日のみビルドする
          # UTCで記述する事、この場合は日本時間 20 時にしたいので -9 して 11 にしてある
          cron: "0 11 * * 0"
          filters:
            branches:
              only:
                - develop
    jobs:
      # - build_android_m75_16
      - build_ios_m75_16
