name: Build

on:
  push:
    paths-ignore:
    - '*.md'
  schedule:
  - cron: "0 0 * * *"

jobs:
  build-ios:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: develop
    - name: Build
      run: make ios

